ERROR - 2023-07-20 21:04:59 --> mysqli_sql_exception: Unknown column 'users.deleted_at' in 'where clause' in /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(295): mysqli->query()
#1 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate()
#8 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt()
#9 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
#11 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
#12 /var/www/html/MyWork/uas/WebJadwal/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/var/www/html/M...')
#14 {main}
CRITICAL - 2023-07-20 21:04:59 --> Unknown column 'users.deleted_at' in 'where clause'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 295.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(295): mysqli->query()
 2 SYSTEMPATH/Database/BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute()
 3 SYSTEMPATH/Database/BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery()
 4 SYSTEMPATH/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
 5 SYSTEMPATH/Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH/BaseModel.php(656): CodeIgniter\Model->doFirst()
 7 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 8 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate()
 9 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt()
10 SYSTEMPATH/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
11 SYSTEMPATH/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
12 SYSTEMPATH/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
13 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/var/www/html/MyWork/uas/WebJadwal/public/index.php')
ERROR - 2023-07-20 21:07:03 --> mysqli_sql_exception: Unknown column 'users.deleted_at' in 'where clause' in /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(295): mysqli->query()
#1 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate()
#8 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt()
#9 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
#11 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
#12 /var/www/html/MyWork/uas/WebJadwal/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/var/www/html/M...')
#14 {main}
CRITICAL - 2023-07-20 21:07:03 --> Unknown column 'users.deleted_at' in 'where clause'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 295.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(295): mysqli->query()
 2 SYSTEMPATH/Database/BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute()
 3 SYSTEMPATH/Database/BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery()
 4 SYSTEMPATH/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
 5 SYSTEMPATH/Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH/BaseModel.php(656): CodeIgniter\Model->doFirst()
 7 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 8 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate()
 9 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt()
10 SYSTEMPATH/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
11 SYSTEMPATH/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
12 SYSTEMPATH/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
13 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/var/www/html/MyWork/uas/WebJadwal/public/index.php')
ERROR - 2023-07-20 21:08:25 --> mysqli_sql_exception: Unknown column 'users.deleted_at' in 'where clause' in /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(295): mysqli->query()
#1 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate()
#8 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt()
#9 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
#11 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
#12 /var/www/html/MyWork/uas/WebJadwal/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/var/www/html/M...')
#14 {main}
CRITICAL - 2023-07-20 21:08:25 --> Unknown column 'users.deleted_at' in 'where clause'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 295.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(295): mysqli->query()
 2 SYSTEMPATH/Database/BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute()
 3 SYSTEMPATH/Database/BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery()
 4 SYSTEMPATH/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
 5 SYSTEMPATH/Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH/BaseModel.php(656): CodeIgniter\Model->doFirst()
 7 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 8 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate()
 9 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt()
10 SYSTEMPATH/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
11 SYSTEMPATH/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
12 SYSTEMPATH/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
13 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/var/www/html/MyWork/uas/WebJadwal/public/index.php')
ERROR - 2023-07-20 21:08:48 --> mysqli_sql_exception: Unknown column 'users.deleted_at' in 'where clause' in /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(295): mysqli->query()
#1 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate()
#8 /var/www/html/MyWork/uas/WebJadwal/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt()
#9 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
#11 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
#12 /var/www/html/MyWork/uas/WebJadwal/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /var/www/html/MyWork/uas/WebJadwal/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/var/www/html/M...')
#14 {main}
CRITICAL - 2023-07-20 21:08:48 --> Unknown column 'users.deleted_at' in 'where clause'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 295.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(295): mysqli->query()
 2 SYSTEMPATH/Database/BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute()
 3 SYSTEMPATH/Database/BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery()
 4 SYSTEMPATH/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
 5 SYSTEMPATH/Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH/BaseModel.php(656): CodeIgniter\Model->doFirst()
 7 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 8 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate()
 9 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt()
10 SYSTEMPATH/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
11 SYSTEMPATH/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
12 SYSTEMPATH/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
13 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/var/www/html/MyWork/uas/WebJadwal/public/index.php')
CRITICAL - 2023-07-20 21:11:38 --> syntax error, unexpected ';', expecting ')'
in APPPATH/Config/Routes.php on line 34.
 1 SYSTEMPATH/CodeIgniter.php(800): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH/CodeIgniter.php(447): CodeIgniter\CodeIgniter->tryToRouteIt()
 3 SYSTEMPATH/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/var/www/html/MyWork/uas/WebJadwal/public/index.php')
CRITICAL - 2023-07-20 21:11:42 --> syntax error, unexpected ';', expecting ')'
in APPPATH/Config/Routes.php on line 34.
 1 SYSTEMPATH/CodeIgniter.php(800): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH/CodeIgniter.php(447): CodeIgniter\CodeIgniter->tryToRouteIt()
 3 SYSTEMPATH/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/var/www/html/MyWork/uas/WebJadwal/public/index.php')
CRITICAL - 2023-07-20 21:11:45 --> syntax error, unexpected ';', expecting ')'
in APPPATH/Config/Routes.php on line 34.
 1 SYSTEMPATH/CodeIgniter.php(800): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH/CodeIgniter.php(447): CodeIgniter\CodeIgniter->tryToRouteIt()
 3 SYSTEMPATH/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/var/www/html/MyWork/uas/WebJadwal/public/index.php')
